# Generated by Django 5.0.4 on 2024-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
